spring:
  application:
    name: gateway-service
  server:
    port: 9090

  cloud:
    gateway:
      routes:
        # Health Check - Liveness (Sin rate limiting ni circuit breaker)
        - id: payment-health-liveness
          uri: lb://payment-service
          predicates:
            - Path=/payment-service/api/v1/healthcheck/liveness
            - Method=GET
          filters:
            - RewritePath=/payment-service/api/v1/healthcheck/liveness, /api/v1/healthcheck/liveness

        # Health Check - Readiness (Sin rate limiting ni circuit breaker)
        - id: payment-health-readiness
          uri: lb://payment-service
          predicates:
            - Path=/payment-service/api/v1/healthcheck/readiness
            - Method=GET
          filters:
            - RewritePath=/payment-service/api/v1/healthcheck/readiness, /api/v1/healthcheck/readiness

        # Payments endpoint (Con rate limiting y circuit breaker, SIN autenticación)
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment-service/api/v1/payments
            - Method=POST
          filters:
            - RewritePath=/payment-service/api/v1/payments, /api/v1/payments
            # Rate limiting por IP
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10  # 10 requests/segundo
                redis-rate-limiter.burstCapacity: 20  # Máximo 20 en ráfaga
                key-resolver: "#{@rateLimitKeyResolver}"
            # Circuit breaker para resilencia
            - name: CircuitBreaker
              args:
                name: paymentService
                fallbackUri: forward:/fallback/payment

# Eureka client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

# Redis para rate limiting
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

# Logging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.aldob.gateway: DEBUG